Number of Agent Curriculum
GT-STAR-Lab/VectorizedMultiAgentSimulator pull request #26
Opened 2024-05-23 21:26 UTC by piercehowell

2024-05-28 18:33 UTC, kfu02 requested changes
One question

2024-05-28 18:33 UTC, kfu02 commented on vmas/simulator/environment/environment.py
> +    def get_agent_environment_state_space(self, agent: Agent, obs_1: AGENT_OBS_TYPE, obs_2: AGENT_OBS_TYPE):
Does this change always imply we will only have two agents?

2024-05-29 14:18 UTC, piercehowell reviewed
I fixed the function @kfu02 that you had the question on. Although, as of now, the function is not used.

2024-05-29 14:58 UTC, kfu02 approved these changes

2024-05-29 15:05 UTC, merged